[bar/main]
modules-left = bspwm sep xwindow sep ws-mode sep
modules-right = sep filesystem sep cpu sep gpu sep memory sep date sep tray
modules-center = logo
font-0 = "JetBrainsMono Nerd Font:size=12"
wm-restack = bspwm
background = #00000000
offset-y = 5
line-size = 2

; left modules

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
enable-click = true
enable-scroll = false
format = <label-state>
label-active = %icon% %name%
label-active-underline = #ffffff
label-active-padding = 0.5
label-active-minlen = 3
label-occupied-minlen = 3
label-empty-minlen = 3

[module/ws-mode]
type = internal/bspwm
format = [<label-mode>]
label-monocle = M
label-tiled = T
label-fullscreen = F
label-floating = S
label-pseudotiled = P

[module/xwindow]
type = internal/xwindow
format = <label>
label = %title%
label-maxlen = 50

; right modules

[module/date]
type = internal/date
interval = 60.0
date = %a %d %H:%M

[module/tray]
type = internal/tray
format-margin = 8px
tray-spacing = 10px

[module/cpu]
type = internal/cpu
interval = 5.0
format = <label>
label = CPU: %percentage%%

[module/memory]
type = internal/memory
interval = 5.0
format = <label>
label = RAM: %gb_used%

[module/filesystem]
type = internal/fs

mount-0 = /
interval = 5.0
fixed-values = true
format-mounted = <label-mounted>
label-mounted = %mountpoint%: %used%

; center modules

[module/logo]
type = custom/text
format = <label>
label = " "
#format-foreground = #478061

; custom modules
[module/sep]
type = custom/text
format = |
format-padding = 1

[module/gpu]
type = custom/script
exec = cat /sys/class/drm/card0/device/gpu_busy_percent
interval = 1
format-prefix = "GPU: " 
format-suffix = "%"
